/**
 * Custom decoder for the Sky PAU AdministeredAgent, the contract a PAU
 * allocator Safe calls.
 *
 * The call path a signer is asked to approve is four layers deep:
 *
 *   Safe -> MultiSend -> AdministeredAgent.batchCall -> Controller -> facet
 *
 * Nothing but the first two layers decodes without this file. The Controller is
 * a diamond dispatcher: its `fallback` looks up `dispatches[msg.sig]` and
 * delegatecalls a facet with the incoming selector REPLACED by a stored
 * delegate selector. The call selector appears in no published ABI, in no facet
 * source, and in no 4-byte database, because it is chosen when an integration
 * is wired and lives only as on-chain state. The Sourcify fallback therefore
 * cannot help: it fetches the ABI of the call target, which is the Controller,
 * and that ABI holds 11 functions, none of them a wired call selector.
 *
 * This decoder resolves the selector against a frozen copy of that on-chain
 * map — `pau-dispatch-table.ts`, generated by
 * `scripts/generate-pau-dispatch.mjs`. The forwarded argument bytes are
 * unchanged by the Controller, so once the dispatch is known the decoding is
 * exact and the re-encode check applies normally.
 *
 * **What a frozen copy costs.** A stale entry does not fail to decode. It names
 * the wrong facet function while the argument types still round-trip, which is
 * a confident wrong label — the exact failure this tool exists to prevent. Two
 * things bound that risk, and neither lives here:
 *
 *   - the web UI runs one `eth_call` to `getDispatches` and refuses to present
 *     a decoding whose entry disagrees with the chain (`pau-verify.ts`);
 *   - a scheduled workflow diffs the table against the chain daily and opens an
 *     issue on any difference (`.github/workflows/pau-dispatch.yml`).
 *
 * This decoder stays synchronous and pure like every other `CustomDecoder`, so
 * it works offline and in the CLI. It always states the block its table was
 * frozen at.
 *
 * `AdministeredAgent.call(address,bytes)` is deliberately NOT decoded here.
 * Every observed PAU allocator transaction uses `batchCall`, and the
 * AdministeredAgent is verified on Sourcify, so a `call` falls through to the
 * Sourcify fallback rather than to a path this decoder has never seen exercised.
 *
 * Source: https://github.com/sky-ecosystem/diamond-pau
 */

import type { AbiParameter, Address, Hex } from 'viem'
import { decodeFunctionData, parseAbi } from 'viem'
import type { CustomDecoder, DecodedFunction, DecodedTransactionData } from './types.js'
import { checkReencode } from './sky-common.js'
import {
  findPauControllerTable,
  findPauWire,
  describeMaxSlippage,
  readPauAmount,
  PAU_FUNCTION_NOTES,
  PAU_MAX_SLIPPAGE_FUNCTIONS,
  type PauControllerTable,
  type PauWire,
} from './pau-common.js'
import { PAU_DISPATCH_TABLES } from './pau-dispatch-table.js'

/**
 * The one AdministeredAgent function this decoder handles.
 *
 * Transcribed from the source verified on Sourcify,
 * `lib/pau-administered-agent/src/AdministeredAgent.sol:AdministeredAgent`,
 * exact match. `outputs` is omitted: it plays no part in decoding calldata.
 */
const ADMINISTERED_AGENT_ABI = parseAbi([
  'function batchCall(address[] targets, bytes[] data, uint256[] values)',
])

/** `batchCall(address[],bytes[],uint256[])`. */
export const PAU_BATCH_CALL_SELECTOR = '0x4e120423'

/** An AdministeredAgent this decoder is registered for. */
export interface PauAdministeredAgent {
  address: Address
  label: string
  network: string
}

/**
 * The AdministeredAgents in active use.
 *
 * Both were confirmed on 2026-08-20 by reading `actorCount` / `getActor` on
 * each: the allocator Safe appears in the actor list of the agent paired with
 * its Controller. The two contracts have identical runtime bytecode
 * (keccak256 `0xb56e803a74ca3a82b1bff9be86f8aeb1b22a90470c607ee76d510d9cc76a15a9`),
 * so both are the same AdministeredAgent implementation.
 *
 * Which sub-DAO operates `0x1837505D104F7a6D8b7e19452610B0A3D652EF12` and its
 * Controller `0x24169Afb34fAe4D4356BC54Bd80319131e35ca38` was not determined.
 */
export const PAU_ADMINISTERED_AGENTS: readonly PauAdministeredAgent[] = [
  {
    address: '0xdBD17832df0e57b1732cE1C84c652E820e549BAa',
    label: 'Grove PAU AdministeredAgent',
    network: 'ethereum',
  },
  {
    address: '0x1837505D104F7a6D8b7e19452610B0A3D652EF12',
    label: 'PAU AdministeredAgent 0x1837505D104F7a6D8b7e19452610B0A3D652EF12',
    network: 'ethereum',
  },
]

/**
 * Render one decoded argument for display.
 *
 * Numeric scalars stay `bigint` so the UI's decimals picker remains live, which
 * is the right default where the denomination is not source-backed. Tuples and
 * arrays are flattened to a string, in full — no element is ever elided.
 */
function renderValue(input: AbiParameter, value: unknown): string | bigint | boolean {
  if (typeof value === 'bigint') return value
  if (typeof value === 'boolean') return value
  if (Array.isArray(value)) {
    const components: readonly AbiParameter[] =
      'components' in input ? (input.components ?? []) : []
    return `[${value
      .map((item, i) => String(renderValue(components[i] ?? input, item)))
      .join(', ')}]`
  }
  if (value !== null && typeof value === 'object') {
    const components: readonly AbiParameter[] =
      'components' in input ? (input.components ?? []) : []
    return `{${components
      .map(
        component =>
          `${component.name}: ${String(
            renderValue(component, (value as Record<string, unknown>)[component.name ?? ''])
          )}`
      )
      .join(', ')}}`
  }
  return String(value)
}

/**
 * Decoder for a PAU AdministeredAgent `batchCall`.
 *
 * One instance per AdministeredAgent address. The frozen dispatch tables are
 * shared: a batch may target any Controller, and the table is selected by the
 * Controller address in the calldata, not by which agent forwarded the call.
 */
export class PAUAdministeredAgentDecoder implements CustomDecoder {
  readonly contractAddress: Address
  readonly contractName: string
  readonly network: string

  private readonly tables: readonly PauControllerTable[]

  constructor(
    agent: PauAdministeredAgent,
    tables: readonly PauControllerTable[] = PAU_DISPATCH_TABLES
  ) {
    this.contractAddress = agent.address
    this.contractName = agent.label
    this.network = agent.network
    this.tables = tables
  }

  canDecode(to: Address, data: Hex): boolean {
    return (
      to.toLowerCase() === this.contractAddress.toLowerCase() &&
      data.slice(0, 10).toLowerCase() === PAU_BATCH_CALL_SELECTOR
    )
  }

  decode(data: Hex): DecodedTransactionData {
    const { functionName, args } = decodeFunctionData({
      abi: ADMINISTERED_AGENT_ABI,
      data,
    })

    const decodedArgs = (args ?? []) as readonly unknown[]
    const [targets, calls, values] = decodedArgs as [
      readonly Address[],
      readonly Hex[],
      readonly bigint[],
    ]

    // Re-encode and byte-compare the outer call. viem's decoder ignores bytes
    // appended past the end of the encoded arguments, so without this check a
    // transaction carrying extra trailing calldata would render as a clean,
    // ordinary batch.
    const reencode = checkReencode(ADMINISTERED_AGENT_ABI, functionName, decodedArgs, data)

    const nested = targets.map((target, i) =>
      this.decodeControllerCall(target, calls[i] ?? '0x', values[i] ?? 0n, i, targets.length)
    )

    const main = this.describeBatch(targets, calls, values, nested)

    // Anything a nested call flagged is lifted onto the batch, because the
    // nested-call cards in the UI render name, signature, explanation and
    // parameters but not their own warning list.
    const lifted = nested.flatMap(call => call.warnings ?? [])
    if (lifted.length > 0) main.warnings = [...(main.warnings ?? []), ...lifted]
    if (nested.some(call => call.riskLevel === 'high')) main.riskLevel = 'high'

    // A nested re-encode mismatch means the displayed parameters are not the
    // bytes being signed, which is the same category as an outer mismatch.
    const hardFailures = nested.flatMap(call => call.warnings ?? []).filter(isHardFailure)

    if (reencode.status === 'trailing') {
      // Trailing bytes leave the decoded parameters correct, so this is a
      // warning about bytes the display does not cover, not a reason to
      // distrust the display. It stays out of generalWarnings, which the UI
      // renders as "decoder verification failed". See spbeam.ts.
      main.warnings = [...(main.warnings ?? []), ...reencode.warnings]
      if (main.riskLevel !== 'high') main.riskLevel = 'medium'
      return {
        main,
        nested,
        isMulticall: true,
        ...(hardFailures.length > 0 ? { generalWarnings: hardFailures } : {}),
      }
    }

    if (reencode.status !== 'exact') {
      main.warnings = [...(main.warnings ?? []), ...reencode.warnings]
      main.riskLevel = 'high'
      return {
        main,
        nested,
        isMulticall: true,
        generalWarnings: [...reencode.warnings, ...hardFailures],
      }
    }

    return {
      main,
      nested,
      isMulticall: true,
      ...(hardFailures.length > 0 ? { generalWarnings: hardFailures } : {}),
    }
  }

  getSupportedFunctions(): string[] {
    return ['batchCall']
  }

  /** The batch itself: what it forwards, to whom, and in what order. */
  private describeBatch(
    targets: readonly Address[],
    calls: readonly Hex[],
    values: readonly bigint[],
    nested: readonly DecodedFunction[]
  ): DecodedFunction {
    const parameters: DecodedFunction['parameters'] = [
      { name: 'calls', type: 'uint256', value: BigInt(targets.length) },
    ]

    for (let i = 0; i < targets.length; i++) {
      const target = targets[i]
      if (!target) continue
      const label = `call ${i + 1} of ${targets.length}`
      parameters.push({ name: `${label} — target`, type: 'address', value: target })
      parameters.push({
        name: `${label} — call selector`,
        type: 'bytes4',
        value: selectorOf(calls[i] ?? '0x'),
      })
      parameters.push({
        name: `${label} — value`,
        type: 'uint256',
        value: values[i] ?? 0n,
      })
    }

    const lengthsAgree =
      targets.length === calls.length && targets.length === values.length

    const warnings: string[] = []
    if (!lengthsAgree) {
      warnings.push(
        `⚠️ The batch arrays are not the same length: ${targets.length} targets, ` +
          `${calls.length} calldata entries, ${values.length} values. AdministeredAgent ` +
          `requires them to match and reverts otherwise. Verify the raw calldata by hand.`
      )
    }

    const nonZeroValue = values.some(value => value > 0n)
    if (nonZeroValue) {
      warnings.push(
        `⚠️ At least one call in this batch forwards ETH. PAU allocator calls normally ` +
          `forward zero. Confirm every non-zero value above.`
      )
    }

    return {
      name: 'batchCall',
      signature: 'batchCall(address[],bytes[],uint256[])',
      parameters,
      explanation:
        `Forwards ${targets.length} call${targets.length === 1 ? '' : 's'} through the Sky PAU ` +
        `AdministeredAgent ${this.contractAddress}. Each call below shows the function that ` +
        `executes and its arguments.`,
      warnings,
      riskLevel: nested.some(call => call.riskLevel === 'high') ? 'high' : 'medium',
    }
  }

  /**
   * Decode one inner call to a PAU Controller.
   *
   * Every failure path names the reason precisely, because "undecodable" tells
   * a signer nothing about whether to worry.
   */
  private decodeControllerCall(
    target: Address,
    data: Hex,
    value: bigint,
    index: number,
    total: number
  ): DecodedFunction {
    const position = `Call ${index + 1} of ${total}`

    if (data.length < 10) {
      return {
        name: 'call with no selector',
        signature: `${position} — no 4-byte selector`,
        parameters: [
          { name: 'target', type: 'address', value: target },
          { name: 'calldata', type: 'bytes', value: data },
          { name: 'value', type: 'uint256', value },
        ],
        explanation:
          `${position} carries no 4-byte selector, so nothing identifies what it calls.\n\n` +
          `  • Target — ${target}\n` +
          `  • Calldata (full) — ${data}\n\n` +
          `A PAU Controller reverts a call with fewer than four bytes of calldata. Confirm ` +
          `this entry is intended before signing.`,
        warnings: [
          `⚠️ ${position} carries no 4-byte selector. Target ${target}, calldata ${data}. ` +
            `Verify the raw calldata by hand before signing.`,
        ],
        riskLevel: 'high',
      }
    }

    const callSelector = selectorOf(data)
    const table = findPauControllerTable(this.tables, target)

    if (!table) {
      return {
        name: 'unknown Controller',
        signature: `${position} — ${callSelector} on ${target}`,
        parameters: [
          { name: 'target', type: 'address', value: target },
          { name: 'call selector', type: 'bytes4', value: callSelector },
          { name: 'calldata', type: 'bytes', value: data },
          { name: 'value', type: 'uint256', value },
        ],
        explanation:
          `${position} cannot be decoded. This build holds no dispatch table for ` +
          `${target}.\n\n` +
          `  • Target — ${target}\n` +
          `  • Call selector — ${callSelector}\n` +
          `  • Calldata (full) —\n    ${data}\n\n` +
          `A PAU Controller's selector-to-facet mapping is per-Controller ON-CHAIN STATE, not ` +
          `a property of any published ABI. This build carries a frozen copy of that mapping ` +
          `for ${this.tables.length} Controller${this.tables.length === 1 ? '' : 's'}: ` +
          `${this.tables.map(t => t.controller).join(', ')}. ` +
          `${target} is not among them, so nothing here can say what this call executes. ` +
          `Read getDispatch(${callSelector}) on ${target} and decode against the facet it ` +
          `names before signing.`,
        warnings: [
          `⚠️ ${position} targets ${target}, which is not a Controller this build holds a ` +
            `dispatch table for. The call selector ${callSelector} cannot be resolved to a ` +
            `function. Do not sign a call you cannot name.`,
        ],
        riskLevel: 'high',
      }
    }

    const wire = findPauWire(table, callSelector)

    if (!wire) {
      return {
        name: 'unknown call selector',
        signature: `${position} — ${callSelector} on ${target}`,
        parameters: [
          { name: 'Controller', type: 'address', value: target },
          { name: 'call selector', type: 'bytes4', value: callSelector },
          { name: 'calldata', type: 'bytes', value: data },
          { name: 'value', type: 'uint256', value },
        ],
        explanation:
          `${position} cannot be decoded. Call selector ${callSelector} is not in this ` +
          `build's frozen dispatch table for ${table.label} ${table.controller}.\n\n` +
          `  • Controller — ${target}\n` +
          `  • Call selector — ${callSelector}\n` +
          `  • Calldata (full) —\n    ${data}\n\n` +
          `The mapping from a call selector to a facet is per-Controller ON-CHAIN STATE. ` +
          `This build's copy was frozen at block ${table.frozenAtBlock} ` +
          `(${table.frozenAtDate}) and holds ${table.wires.length} selectors. A selector ` +
          `wired after that block is absent from it. Read ` +
          `getDispatch(${callSelector}) on ${table.controller} to find the facet and the ` +
          `delegate selector, then decode against the facet's own verified ABI.`,
        warnings: [
          `⚠️ ${position} uses call selector ${callSelector} on Controller ${target}, which ` +
            `is not in this build's frozen dispatch table (frozen at block ` +
            `${table.frozenAtBlock}, ${table.frozenAtDate}). Do not sign a call you cannot ` +
            `name.`,
        ],
        riskLevel: 'high',
      }
    }

    return this.decodeWiredCall(table, wire, target, data, value, position)
  }

  /** Decode an inner call whose dispatch the frozen table covers. */
  private decodeWiredCall(
    table: PauControllerTable,
    wire: PauWire,
    controller: Address,
    data: Hex,
    value: bigint,
    position: string
  ): DecodedFunction {
    // The Controller forwards msg.data[4:] verbatim under the delegate
    // selector. Rebuilding exactly those bytes is what makes the decode — and
    // the re-encode check below — describe what the facet receives.
    const delegateData = `${wire.delegateSelector}${data.slice(10)}` as Hex

    const warnings: string[] = []
    let args: readonly unknown[] = []
    let decodeFailed: string | null = null

    try {
      const decoded = decodeFunctionData({ abi: [wire.abi], data: delegateData })
      args = (decoded.args ?? []) as readonly unknown[]
    } catch (error) {
      decodeFailed = error instanceof Error ? error.message : String(error)
    }

    const parameters: DecodedFunction['parameters'] = [
      { name: 'Controller', type: 'address', value: controller },
      { name: 'call selector (sent)', type: 'bytes4', value: wire.callSelector },
      { name: 'delegate selector (executed)', type: 'bytes4', value: wire.delegateSelector },
      { name: 'facet', type: 'address', value: wire.facet },
      { name: 'facet contract', type: 'string', value: wire.facetName ?? 'unknown' },
      { name: 'integration id', type: 'bytes32', value: wire.integrationId },
      ...(wire.integrationLabel
        ? [{ name: 'integration', type: 'string', value: wire.integrationLabel }]
        : []),
      { name: 'value', type: 'uint256', value },
    ]

    if (decodeFailed) {
      return {
        name: wire.abi.name,
        signature: wire.signature,
        parameters: [...parameters, { name: 'calldata', type: 'bytes', value: data }],
        explanation:
          `${position} resolves to ${wire.signature} on facet ${wire.facet}, but the ` +
          `forwarded arguments could not be decoded against that function: ${decodeFailed}\n\n` +
          `  • Controller — ${controller}\n` +
          `  • Call selector (sent) — ${wire.callSelector}\n` +
          `  • Delegate selector (executed) — ${wire.delegateSelector}\n` +
          `  • Calldata (full) —\n    ${data}\n\n` +
          `Dispatch table frozen at block ${table.frozenAtBlock} (${table.frozenAtDate}).`,
        warnings: [
          `⚠️ ${position} could not be decoded against ${wire.signature}: ${decodeFailed}. ` +
            `Verify the raw calldata by hand before signing.`,
        ],
        riskLevel: 'high',
      }
    }

    const key = `${wire.facetName}.${wire.signature}`
    const inputs = wire.abi.inputs ?? []
    const domainNotes: string[] = []

    for (let i = 0; i < inputs.length; i++) {
      const input = inputs[i]
      if (!input) continue
      const name = input.name || `arg${i}`
      const raw = args[i]

      if (PAU_MAX_SLIPPAGE_FUNCTIONS.has(key) && i === 1) {
        const reading = describeMaxSlippage(raw as bigint)
        parameters.push({
          name,
          type: input.type,
          value: `${reading.value} — ${reading.meaning}`,
        })
        domainNotes.push(`  • ${name} — ${reading.value}\n    ${reading.meaning}`)
        if (reading.warning) warnings.push(`⚠️ ${position}: ${reading.warning.slice(2).trim()}`)
        continue
      }

      if (typeof raw === 'bigint' && /^uint\d*$/.test(input.type)) {
        const reading = readPauAmount(this.network, wire.facetName, wire.signature, i, raw, args)
        // A bare integer keeps the UI's decimals picker live, which is what a
        // signer needs where the scale is undetermined. A scaled string is only
        // emitted where the facet source pins the denomination.
        parameters.push({
          name,
          type: input.type,
          value: reading.scaled ?? raw,
        })
        domainNotes.push(
          `  • ${name} (${input.type}) — ${reading.scaled ?? raw.toString()}` +
            (reading.note ? ` (${reading.note})` : '')
        )
        continue
      }

      parameters.push({ name, type: input.type, value: renderValue(input, raw) })
      domainNotes.push(`  • ${name} (${input.type}) — ${String(renderValue(input, raw))}`)
    }

    // Re-encode against the bytes the facet receives. The selector swap is the
    // Controller's own behaviour, so proving the decoded arguments reproduce
    // `delegateData` proves they reproduce the signed calldata past its first
    // four bytes, which are shown separately and in full.
    const reencode = checkReencode([wire.abi], wire.abi.name, args, delegateData)
    if (reencode.status !== 'exact') {
      warnings.push(...reencode.warnings.map(warning => `${position}: ${warning}`))
    }

    const note = PAU_FUNCTION_NOTES[key]

    return {
      name: wire.abi.name,
      signature: wire.signature,
      parameters,
      explanation:
        `${position} executes ${wire.signature} on ${wire.facetName ?? 'an unnamed facet'}.\n\n` +
        `  • Controller — ${controller}\n` +
        `  • Call selector (sent) — ${wire.callSelector}\n` +
        `  • Delegate selector (executed) — ${wire.delegateSelector}\n` +
        `  • Facet — ${wire.facet}\n` +
        `  • Integration id — ${wire.integrationId}` +
        (wire.integrationLabel ? ` (${wire.integrationLabel})` : '') +
        `\n\n` +
        `Arguments:\n${domainNotes.join('\n')}\n\n` +
        (note ? `${note}\n\n` : '') +
        `The Controller does not execute ${wire.callSelector}. It replaces that selector with ` +
        `${wire.delegateSelector} and delegatecalls ${wire.facet}, forwarding the argument ` +
        `bytes unchanged.\n\n` +
        `Dispatch table frozen at block ${table.frozenAtBlock} (${table.frozenAtDate}); not ` +
        `verified against the chain by this decoder. The web UI checks it against ` +
        `getDispatches on the Controller before presenting it.`,
      warnings,
      riskLevel:
        reencode.status === 'mismatch' || reencode.status === 'unverifiable'
          ? 'high'
          : isStateChanging(wire)
            ? 'medium'
            : 'low',
    }
  }
}

/** Build one decoder per known AdministeredAgent. */
export function createPauAgentDecoders(
  tables: readonly PauControllerTable[] = PAU_DISPATCH_TABLES
): PAUAdministeredAgentDecoder[] {
  return PAU_ADMINISTERED_AGENTS.map(agent => new PAUAdministeredAgentDecoder(agent, tables))
}

/** The full 4-byte selector of a call, or `0x` when there is none. */
function selectorOf(data: Hex): Hex {
  return (data.length >= 10 ? data.slice(0, 10).toLowerCase() : '0x') as Hex
}

function isStateChanging(wire: PauWire): boolean {
  return wire.stateMutability !== 'view' && wire.stateMutability !== 'pure'
}

/** Warnings that mean the display does not describe the signed bytes. */
function isHardFailure(warning: string): boolean {
  return warning.includes('DECODED DATA DOES NOT MATCH RAW CALLDATA')
}
